global using System.Collections.Immutable;
global using System.Runtime.CompilerServices;
global using System.Threading.Tasks;
global using Mew.CodeAnalysis;
global using Mew.Testing;
global using Shouldly;
global using VerifyTests;
global using VerifyXunit;
global using Xunit;