global using System.Collections.Concurrent;
global using System.Diagnostics;
global using MediatR;
global using Mew.CodeAnalysis;
global using Mew.LangServer.Handlers;
global using Mew.LangServer.Outline;
global using Mew.LangServer.Text;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using OmniSharp.Extensions.LanguageServer.Protocol;
global using OmniSharp.Extensions.LanguageServer.Protocol.Client.Capabilities;
global using OmniSharp.Extensions.LanguageServer.Protocol.Document;
global using OmniSharp.Extensions.LanguageServer.Protocol.Models;
global using OmniSharp.Extensions.LanguageServer.Protocol.Server;
global using OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities;
global using OmniSharp.Extensions.LanguageServer.Protocol.Window;
global using OmniSharp.Extensions.LanguageServer.Server;
global using Spectre.Console.Cli;
global using Diagnostic = Mew.CodeAnalysis.Diagnostic;
global using OmnisharpDiagnostic = OmniSharp.Extensions.LanguageServer.Protocol.Models.Diagnostic;
